import type { Metadata } from 'next';
import ThemeRegistry from '@/components/ThemeRegistry';
import AppShell from '@/components/AppShell'; 
import { SITE_NAME } from '@/constants';
import ClientTitleUpdater from '@/components/ClientTitleUpdater'

export const metadata: Metadata = {
  title: {
    template: `${SITE_NAME} - %s`, 
    default: SITE_NAME,         
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <ThemeRegistry>
          <ClientTitleUpdater/>
          <AppShell>
            {children}
          </AppShell>
        </ThemeRegistry>
      </body>
    </html>
  );
}